theme = "dark_plus"

[editor]
cursorline = true
auto-format = false
color-modes = true
gutters = ["diagnostics", "diff"]
lsp.display-messages = true
indent-guides.render = true
bufferline = "multiple"
soft-wrap.enable = true
statusline.right = ["workspace-diagnostics", "diagnostics", "selections", "position-percentage", "position", "file-encoding"]